services:
  db:
    image: postgres:17 
    container_name: database
    environment:
      - POSTGRES_USER=intro  
      - POSTGRES_PASSWORD=ultra_secure_password
      - POSTGRES_DB=dragonball
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data  

    